/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculty.feedback.system;

import static faculty.feedback.system.FacultyFeedbackSystem.formNumber;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import static faculty.feedback.system.FacultyFeedbackSystem.DB_URL;
import static faculty.feedback.system.FacultyFeedbackSystem.USER;
import static faculty.feedback.system.FacultyFeedbackSystem.PASS;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.io.*;
/**
 *
 * @author rudolf
 */
public class FacultyDataG extends javax.swing.JFrame {

    /**
     * Creates new form FacultyDataG
     */
    public FacultyDataG() {
        initComponents();
       
        diplayfac();
        
    }
public  void diplayfac() 
{
    
    String sql; 
       int columnAccess=6;
       columnAccess*=formNumber;
       //String Dep[]={"BT","CS","ME","EE","EC"};
        try 
        {
            Connection conn = DriverManager.getConnection(DB_URL,USER,PASS);   
            Statement stmt = conn.createStatement();
            PrintName.setText(FacultyData.eName);
           // for(int z=0;z<5;z++)
            {
                
                //sql = "Select * FROM `"+Dep[z]+"` WHERE `Name`='"+FacultyData.eName+"';";
              // ResultSet rs = stmt.executeQuery(sql);
                sql="";
                ResultSet rs = null;
                 PreparedStatement prepstmt = null;
                switch(formNumber)
                {
                    //sql = "Select `Class`, `Subject`, `SEM`, `F1Q1`, `F1Q2`, `F1Q3`, `F1Q4`, `F1Q5`, `Form 1` FROM `"+FacultyData.eDEP+"` WHERE `Name`='"+FacultyData.eName+"';";
                    case 1: 
                        sql = "Select `Class`, `Subject`, `SEM`, `F1Q1`, `F1Q2`, `F1Q3`, `F1Q4`, `F1Q5`, `Form 1` FROM `"+FacultyData.eDEP+"` WHERE `Name`='"+FacultyData.eName+"';";
                         break;
                    case 2 :
                        sql = "Select `Class`, `Subject`, `SEM`, `F2Q1`, `F2Q2`, `F2Q3`, `F2Q4`, `F2Q5`, `Form 2` FROM `"+FacultyData.eDEP+"` WHERE `Name`='"+FacultyData.eName+"';";
                        break;
                    case 3:
                        sql = "Select `Class`, `Subject`, `SEM`, `F3Q1`, `F3Q2`, `F3Q3`, `F3Q4`, `F3Q5`, `Form 3` FROM `"+FacultyData.eDEP+"` WHERE `Name`='"+FacultyData.eName+"';";
                        break;
                }
                
                 
                 prepstmt = conn.prepareStatement(sql);
                 rs = prepstmt.executeQuery();
                //if(rs.next())
                {
                      
                      FcultyDataTable.setModel(DbUtils.resultSetToTableModel(rs));   
                }
             
            }
            int j=100;
        
         
           
             
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    
}
public void WFile()
{
    BufferedWriter bw = null;
		FileWriter fw = null;
                try {

			//String data = " This is new content";
                        String k=FacComplaint.getText();
            k=FacultyData.eName+"\t"+Date.Date()+"\t"+Time.Time()+"\n"+k+"\n\n";

			File file = new File("FacultyComplaint"+FacultyData.eDEP+".txt");

			// if file doesnt exists, then create it
			if (!file.exists()) {
				file.createNewFile();
			}

			// true = append file
			fw = new FileWriter(file.getAbsoluteFile(), true);
			bw = new BufferedWriter(fw);

			bw.write(k);

			System.out.println("Done");

		} catch (IOException e) {

			e.printStackTrace();
                }finally {

			try {

				if (bw != null)
					bw.close();

				if (fw != null)
					fw.close();

			} catch (IOException ex) {

				ex.printStackTrace();

			}
                }
                        

   /* try {
         String k=FacComplaint.getText();
            k=FacultyData.eName+"\n"+Time.Time()+k+"\n\n";
            
            char buffer[]=new char [k.length()];
            k.getChars(0,k.length(),buffer,0);
            FileWriter f = new FileWriter ("FacultyComplaint.docx");
            for(int i=0;i<buffer.length;i+=2)
            {
                f.write(buffer[i]);
            }
    }
    
     catch(Exception e)
        {
            e.printStackTrace();
        }*/
    
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FcultyDataTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        PrintName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FacComplaint = new javax.swing.JTextArea();
        SubmitComplaintFaculty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Adobe Caslon Pro", 0, 10)); // NOI18N

        jScrollPane1.setOpaque(false);

        FcultyDataTable.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 14)); // NOI18N
        FcultyDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Class", "Subject", "Semester", "Question 1", "Question 2", "Question 3", "Question 4", "Question 5", "Average"
            }
        ));
        FcultyDataTable.setRowHeight(25);
        jScrollPane1.setViewportView(FcultyDataTable);
        if (FcultyDataTable.getColumnModel().getColumnCount() > 0) {
            FcultyDataTable.getColumnModel().getColumn(1).setMinWidth(30);
        }

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faculty/feedback/system/FacultyData.jpg"))); // NOI18N

        PrintName.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faculty/feedback/system/Icons/Ok Filled-32.png"))); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel9.setText("Question 3 :Depth in Subject");

        jLabel10.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel10.setText("Question 4 :Control over Class ");

        jLabel8.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel8.setText("Question 2 :Audibility ");

        jLabel11.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel11.setText("Question 5 :Availability after class hours");

        jLabel7.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel7.setText("Question 1 :Punctuality");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel1.setText("If you have any complaints, please do list them below. Then click on Submit. If you do not have any complaints then click Done.");

        jScrollPane2.setOpaque(false);

        FacComplaint.setColumns(20);
        FacComplaint.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        FacComplaint.setRows(5);
        jScrollPane2.setViewportView(FacComplaint);

        SubmitComplaintFaculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faculty/feedback/system/Icons/Enter-32.png"))); // NOI18N
        SubmitComplaintFaculty.setText("Submit");
        SubmitComplaintFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitComplaintFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrintName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SubmitComplaintFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(310, 310, 310)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrintName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SubmitComplaintFaculty))
                .addGap(212, 212, 212))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         MainMenu obj1 = new MainMenu();
                obj1.setVisible(true);
                close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitComplaintFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitComplaintFacultyActionPerformed
        // TODO add your handling code here:
        try{
            
            Connection conn = DriverManager.getConnection(DB_URL,USER,PASS);   
            Statement stmt = conn.createStatement();
            String ab=FacComplaint.getText();
            ab = ab.replaceAll(" ","");
             ab=ab.replaceAll("\n","");
             ab=ab.replaceAll("\t","");
             if(!("".equals(ab)))
             {
                 WFile();
         //  String sql="SELECT FROM `HODS` WHERE `DEP`="+FacultyData.eDEP+"";
          //  ResultSet  rs = stmt.executeQuery(sql);
           //rs.next();
          // int noti=rs.getInt(7);
         //  noti ++;
         //  stmt.executeUpdate("Update `HODS` SET `Notify Faculty`='"+noti+"' WHERE `DEP`='"+FacultyData.eDEP+"';");
           JOptionPane.showMessageDialog(null, "We will look into this matter and get back to you shortly");
          // MainMenu obj1 = new MainMenu();
          // obj1.setVisible(true);
          // close(); 
             }
           JOptionPane.showMessageDialog(null, "If you have no remarks please click the Done button");

        }
        catch(Exception e )
        {
            
        }
        
      
                
    }//GEN-LAST:event_SubmitComplaintFacultyActionPerformed
public void close()
    {
        WindowEvent wce = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wce);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wce);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyDataG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyDataG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyDataG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyDataG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyDataG().setVisible(true);
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FacComplaint;
    private javax.swing.JTable FcultyDataTable;
    private javax.swing.JLabel PrintName;
    private javax.swing.JButton SubmitComplaintFaculty;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
